import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="font-primary flex flex-col items-center justify-center"
    >
      <body
        className={`mt-14 overflow-x-hidden flex w-[100%] max-w-screen-2xl flex-col gap-y-20 px-8 ${inter.className}`}
      >
        <Navbar />

        {children}
      {/* empty placeholder to make the bottom of the page more spacious*/}
      <div className="h-96"></div>
      </body>
    </html>
  );
}
